### ISSUE TITLE
Clicking Datepicker month selection arrows don't work as expected

### ISSUE THREAD

**Issue by gthomas3** [mskocik/svelty-picker#19] opened 2022-01-25 22:28 UTC
One of the last significant issues I've run into is the clickable up/down month navigation arrows don't work in my local instance. However I see they are working in the github.io and REPL.

Do you know of anything that may lead to this? Adjusting my timezone doesn't seem to have an impact.

Clicking the current month, then selecting another month works, as does using the keyboard up/down arrows to traverse months.

This is my actual implementation
```
      <SveltyPicker
        format="M d, yyyy hh:ii"
        placeholder="End date/time"
        inputClasses={`w-full min-h-[50px] pl-3 bg-white rounded border border-solid border-[#d9d9d9] ${
          isPastScheduleReadOnlyView
            ? "cursor-default text-[#00000061]"
            : "cursor-pointer"
        }`}
        weekStart={0}
        initialDate={$endDateTime.value}
        disabled={isPastScheduleReadOnlyView}
        bind:value={$endDateTime.value}
      />
```

I've copied the exact REPL implementation, and still experience the same behaviour
```  
let myDate = '2021-11-11 14:35';

<SveltyPicker format="yyyy-mm-dd hh:ii" bind:value={myDate}></SveltyPicker>
```

**Comment by mskocik** [comment] 2022-01-26 07:15
Cannot it be a CSS issue? Are those buttons receiving the click event? Must be related to something specific in your project. If you could provide working repo, we could find out more easily.

**Comment by mskocik** [comment] 2022-01-26 15:28
And if you manually call `dataset = compute(...)` on line `Calendar.svelte:156`? 

Will it work?

**Comment by gthomas3** [comment] 2022-01-26 16:53
Yeah, works partially.

dataset is updated and the dates in the calendar update.

The name of the month in the top left doesn't change. Stays as January.

**Comment by mskocik** [comment] 2022-01-26 17:04
That is weird. It seems, like `activeDate` assignment is not triggering reactivity updates. Therefore you have no month label update.

The only question is what svelte version are you using? And if updating some svelte related dependencies wouldn't help. 🤔

**Comment by gthomas3** [comment] 2022-01-26 17:44
Yeah, exactly.

I thought the same; was running 3.42.3 when the issues arose, so I updated to the latest 3.46.2. Really bizarre.

**Comment by mskocik** [comment] 2022-01-27 08:13
The only way I could potentially help is when you provide reproducible repo. Otherwise I have no idea. Maybe some edge-case svelte internal bug?

**Comment by gthomas3** [comment] 2022-01-27 14:59
Ugh, finally got it. We're using Vite with the `@sveltejs/vite-plugin-svelte` plugin.

It's caused by one of the compile time Svelte options.

```
  compilerOptions: {
    immutable: true,
  },
```
https://svelte.dev/docs#compile-time-svelte-compile.

Sorry for the wild-goose chase, greatly appreciate your prompt help!

Hope this helps anyone in the future.

**Comment by mskocik** [comment] 2022-01-28 16:00
I am closing this, because I think this should be resolved (I opened another issue for it). Thanks for pointing this out.

**Closed by mskocik** 2022-01-28 16:00 UTC
